import os
from dotenv import load_dotenv

load_dotenv()

# AP
TELEGRAM_TOKEN = "YOUR BOT TOKEN"
MODELSCOPE_API_KEY = "YOUR MOBBLESCOPE API KEY"

# ADMINS
ADMINS =[7840721626]

# LIMITS
QUESTION_COOLDOWN = 30
MAX_QUESTIONS_PER_DAY = 20

# ANTIFLOOD
FLOOD_LIMIT = 5
FLOOD_INTERVAL = 10

